### ISSUE TITLE
MySQL database error

### ISSUE THREAD

**Issue by sainio** [BobAtchley/weewx-ws6in1#12]
Not sure if this is driver issue or weewx, but mysql connection seems to work fine with Simulator.

Traceback (most recent call last):
  File "/home/weewx/bin/weedb/mysql.py", line 54, in guarded_fn
    return fn(*args, **kwargs)
  File "/home/weewx/bin/weedb/mysql.py", line 266, in execute
    self.cursor.execute(mysql_string, tuple(sql_tuple))
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.DataError: (1264, "Out of range value for column 'sumtime' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weewx/bin/weewxd", line 264, in <module>
    main()
  File "/home/weewx/bin/weewxd", line 157, in main
    engine.run()
  File "/home/weewx/bin/weewx/engine.py", line 178, in run
    self.dispatchEvent(weewx.Event(weewx.STARTUP))
  File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
    callback(event)
  File "/home/weewx/bin/weewx/engine.py", line 574, in startup
    self._catchup(self.engine.console.genStartupRecords)
  File "/home/weewx/bin/weewx/engine.py", line 692, in _catchup
    origin='hardware'))
  File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
    callback(event)
  File "/home/weewx/bin/weewx/engine.py", line 668, in new_archive_record
    log_failure=self.log_failure)
  File "/home/weewx/bin/weewx/manager.py", line 291, in addRecord
    self._addSingleRecord(record, cursor, log_success, log_failure)
  File "/home/weewx/bin/weewx/manager.py", line 999, in _addSingleRecord
    self._set_day_summary(_day_summary, record['dateTime'], cursor)
  File "/home/weewx/bin/weewx/manager.py", line 1447, in _set_day_summary
    cursor.execute(_sql_replace_str, _write_tuple)
  File "/home/weewx/bin/weedb/mysql.py", line 63, in guarded_fn
    raise klass(e)
weedb.DatabaseError: (1264, "Out of range value for column 'sumtime' at row 1")

**Comment by sainio** [comment]
REC:    2018-01-13 00:30:00 EET (1515796200) altimeter: 1013.2021742295456, appTemp: 22.270854454679487, barometer: 1012, cloudbase: 1888.2871588626504, dateTime: 1515796200, dayRain: 0.508, dewpoint: 7.6, ET: None, extraHumid1: None, extraHumid2: None, extraHumid3: None, extraHumid4: None, extraHumid5: None, extraHumid6: None, extraHumid7: None, extraTemp1: None, extraTemp2: None, extraTemp3: None, extraTemp4: None, extraTemp5: None, extraTemp6: None, extraTemp7: None, heatindex: 24.4, humidex: 23.099392618824865, inDewpoint: 7.6850871636145985, inHumidity: 34, inTemp: 24.6, interval: 0, maxSolarRad: 0.0, outHumidity: 38, outTemp: 22.8, pressure: 1007, rain: 0.0, rainRate: 0.508, usUnits: 17, UV: 0, windchill: 22.799999999999997, windDir: None, windGust: 0.0, windrun: 0.0, windSpeed: 0.0
REC:    2016-12-31 01:00:00 EET (1483138800) altimeter: 1013.2021742295456, appTemp: 24.42258412539079, barometer: 1012, cloudbase: 2117.828638662358, dateTime: 1483138800, dayRain: 0.508, dewpoint: 7.9, ET: None, extraHumid1: None, extraHumid2: None, extraHumid3: None, extraHumid4: None, extraHumid5: None, extraHumid6: None, extraHumid7: None, extraTemp1: None, extraTemp2: None, extraTemp3: None, extraTemp4: None, extraTemp5: None, extraTemp6: None, extraTemp7: None, heatindex: 25.0, humidex: 25.287329316429165, inDewpoint: 8.154329272367196, inHumidity: 31, inTemp: 26.7, interval: 0, maxSolarRad: 0.0, outHumidity: 34, outTemp: 24.9, pressure: 1007, rain: 0.0, rainRate: 0.508, usUnits: 17, UV: 0, windchill: 24.899999999999995, windDir: None, windGust: 0.0, windrun: 0.0, windSpeed: 0.0
REC:    2016-12-31 01:30:00 EET (1483140600) altimeter: 1013.2021742295456, appTemp: 25.043015310717536, barometer: 1012, cloudbase: 2180.6122520201493, dateTime: 1483140600, dayRain: 0.508, dewpoint: 8.0, ET: None, extraHumid1: None, extraHumid2: None, extraHumid3: None, extraHumid4: None, extraHumid5: None, extraHumid6: None, extraHumid7: None, extraTemp1: None, extraTemp2: None, extraTemp3: None, extraTemp4: None, extraTemp5: None, extraTemp6: None, extraTemp7: None, heatindex: 25.5, humidex: 25.922069034388365, inDewpoint: 6.983319553081113, inHumidity: 30, inTemp: 25.9, interval: 1800, maxSolarRad: 0.0, outHumidity: 33, outTemp: 25.5, pressure: 1007, rain: 0.0, rainRate: 0.0, usUnits: 17, UV: 0, windchill: 25.500000000000004, windDir: None, windGust: 0.0, windrun: 0.0, windSpeed: 0.0
Traceback (most recent call last):
  File "/home/weewx/bin/weedb/mysql.py", line 54, in guarded_fn
    return fn(*args, **kwargs)
  File "/home/weewx/bin/weedb/mysql.py", line 266, in execute
    self.cursor.execute(mysql_string, tuple(sql_tuple))
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.DataError: (1264, "Out of range value for column 'sumtime' at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weewx/bin/weewxd", line 264, in <module>
    main()
  File "/home/weewx/bin/weewxd", line 157, in main
    engine.run()
  File "/home/weewx/bin/weewx/engine.py", line 178, in run
    self.dispatchEvent(weewx.Event(weewx.STARTUP))
  File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
    callback(event)
  File "/home/weewx/bin/weewx/engine.py", line 574, in startup
    self._catchup(self.engine.console.genStartupRecords)
  File "/home/weewx/bin/weewx/engine.py", line 692, in _catchup
    origin='hardware'))
  File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
    callback(event)
  File "/home/weewx/bin/weewx/engine.py", line 668, in new_archive_record
    log_failure=self.log_failure)
  File "/home/weewx/bin/weewx/manager.py", line 291, in addRecord
    self._addSingleRecord(record, cursor, log_success, log_failure)
  File "/home/weewx/bin/weewx/manager.py", line 999, in _addSingleRecord
    self._set_day_summary(_day_summary, record['dateTime'], cursor)
  File "/home/weewx/bin/weewx/manager.py", line 1447, in _set_day_summary
    cursor.execute(_sql_replace_str, _write_tuple)
  File "/home/weewx/bin/weedb/mysql.py", line 63, in guarded_fn
    raise klass(e)
weedb.DatabaseError: (1264, "Out of range value for column 'sumtime' at row 1")
